export const WORKFLOW_ACTIONS = {
  CREATE_LEAD: "CREATE_LEAD",
  MARK_MEETING: "MARK_MEETING",
  UPLOAD_AUDIO: "UPLOAD_AUDIO",
  VERIFY_LEAD: "VERIFY_LEAD",
  ALLOCATE_LEAD: "ALLOCATE_LEAD",
  AUDIO_COMPLETED: "AUDIO_COMPLETED",
  CLAIM_LEAD: "CLAIM_LEAD",
} as const;

export type WorkflowAction =
  (typeof WORKFLOW_ACTIONS)[keyof typeof WORKFLOW_ACTIONS];
